apiVersion: v1
kind: Pod
metadata:
  name: pod-08
  labels:
    appName: nginx
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    appName: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-08-sleep
spec:
  containers:
    - name: test
      image: docker.io/rkalluru/centos-sleep

