apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  volumes:
    - name: vault
      emptyDir:
        sizeLimit: 5Mi
  initContainers:
    - name: vault
      image: 471112738465.dkr.ecr.us-east-1.amazonaws.com/vault-init-container:v2
      env:
        - name: VAULT_ADDR
          value: "https://vault-internal.psrikanth.online:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: SECRET_NAME
          value: expense-dev/backend
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"
      volumeMounts:
        - mountPath: /data
          name: vault
  containers:
    - name: backend
      image: 471112738465.dkr.ecr.us-east-1.amazonaws.com/expense-backend:2.0.2
      volumeMounts:
        - mountPath: /data
          name: vault
